CREATE DATABASE [Subscription]
USE [Subscription]
GO
/****** Object:  Table [dbo].[SUBSCRIPTION]    Script Date: 12/5/2022 2:49:08 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SUBSCRIPTION](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[SUBSCRIBER_NAME] [varchar](255) NOT NULL,
	[DATE_SUBSCRIBED] [datetime] NULL,
	[DATE_RETURNED] [datetime] NULL,
	[BOOK_ID] [varchar](255) NOT NULL
) ON [PRIMARY]
GO
/****** Object:  StoredProcedure [dbo].[GETSUBSCRIPTIONS]    Script Date: 12/5/2022 2:49:08 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[GETSUBSCRIPTIONS]
AS
BEGIN
SELECT 
	ID,SUBSCRIBER_NAME, DATE_SUBSCRIBED, DATE_RETURNED, BOOK_ID 
FROM SUBSCRIPTION
END
GO
/****** Object:  StoredProcedure [dbo].[SAVESUBSCRIPTION]    Script Date: 12/5/2022 2:49:08 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create PROCEDURE [dbo].[SAVESUBSCRIPTION]
(
@BookId varchar(50),
@SubscriberName varchar(255),
@DateSubscribed Date
)
AS
BEGIN
INSERT INTO SUBSCRIPTION (SUBSCRIBER_NAME,DATE_SUBSCRIBED,BOOK_ID) VALUES(@SubscriberName,@DateSubscribed,@BookId)
END


GO
